version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_namenode_rpc-address=hdfs-namenode:9000
      - HDFS_CONF_dfs_namenode_http-address=hdfs-namenode:9870
    ports:
      - "9870:9870"
    volumes:
      - hdfs_namenode:/hadoop/dfs/namenode

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_datanode_address=hdfs-datanode:9866
      - HDFS_CONF_dfs_datanode_http-address=hdfs-datanode:9864
      - HDFS_CONF_dfs_datanode_ipc-address=hdfs-datanode:9867
    volumes:
      - hdfs_datanode:/hadoop/dfs/datanode
    depends_on:
      - hdfs-namenode

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8501:8501"

volumes:
  hdfs_namenode:
  hdfs_datanode:
  mongodb_data:
